language: c

before_install:
  - apt-get -qq update
  - apt-get install -y libgmp3-dev libmpfr-dev libmpc-dev nasm
  - .ci/get-cmake.sh

before_script:
  - toolchain/build.sh
  - mkdir build
  - cd build
  - cmake ../

script: make

cache:
  directories:
    - toolchain/usr
